### ISSUE TITLE
Make MNE an optional dependency

### ISSUE THREAD

**Issue by bthirion** [Parietal-INRIA/hidimstat#4]
This currently breaks the build.
```
ERROR: Could not find a version that satisfies the requirement vtk==9.0.20210612.dev0 (from versions: 9.0.1, 9.0.2, 9.0.3, 9.1.0rc1, 9.1.0rc2, 9.1.0rc4, 9.1.0, 9.2.0rc1, 9.2.0rc2)
ERROR: No matching distribution found for vtk==9.0.20210612.dev0
Error: Process completed with exit code 1.
```

**Comment by tbng** [comment]
I checked and MNE is actually an optional dependency at the moment (only iniside the doc_requirements.txt). The build broke because of some forcing dependency in github workflow file, which has been resolved in PR#6  .
